services:
  db:
    image: postgres:16
    container_name: todo-app-db
    restart: always
    environment:
      POSTGRES_DB: todo_app
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - "todo-app-data:/var/lib/postgresql/data"
volumes:
  todo-app-data:
    driver: local
